on: push
jobs: 
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run setup-java with the cache for maven
        uses: ./
        id: setup-java
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: Build with maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=javaprojectreachabilityparreira -Dsonar.organization=javaprojectreachabilityparreira -Dsonar.host.url=https://sonarcloud.io - Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
